version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "terraform"
    reviewers:
      - "shuhei0720"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
